

# Transformation von Polarkoordinaten zu kartesischen
  Koordinaten

Schreiben sie eine \python-\pyref{Funktion}{def}

		kreis(r,mx,my,phi),

welche die $x$- und $y$-Werte (°x°,°y°) für einen Kreis berechnet, der durch die 
Parameterdarstelllung 
$$
\begin{aligned}
  x & = & m_x + r * cos(\phi) \\
  y & = & m_y + r * sin(\phi)
\end{aligned}
$$
beschrieben wird.


