
 
# Rechnen mit Vektoren
Führen Sie im \matlab-Skript °vectorc° einige einfache Definitionen von Variablen durch. Dabei sollen den Variablen
folgende Werte zugewiesen werden:

----|-----------------------------------------
°x° | Vektor der ganzen Zahlen von $1$ bis $5$ 
°y° | Vektor der ganzen Zahlen von $2$ bis $6$ 
°a° | $2.5$
°b° | $3.1$ 

Führen Sie mit diesen Variablen einfache Rechnungen aus und achten Sie dabei auf die Verwendung der richtigen Operatoren (\matrefe{arithmeticoperators}):


-----|-----------------------------------------
°r1° |     $x + y$  
°r2° |     $x \cdot y$  
°r3° |     $x / y$  
°r4° |     $x^y$  
°r5° |     $x / a$  
°r6° |     $a / x$  
°r7° |     $a / (x + b)$  
°r8° |     $x^{y + a}$  
°r9° |     $(x+b)^y$  



