

# Korrektur von Fehlern - P3
Korrigieren sie mit dem \matlab-Skript °fehler1korr.m° folgendes falsches
Programm, das mit vielen Fehlern versehen ist: °fehler1.m°. Öffnen Sie
im Tab Extrafiles °fehler1.m° und fügen Sie dessen Inhalt mit Copy und
Paste in °fehler1korr.m°. Bessern Sie dann die Fehler im
Skript °fehler1korr.m° aus.

\hw

Es soll nur das Programm °fehler1korr.m° geschrieben werden. Lassen Sie
°fehler1.m° so wie es ist.


