# Einfache Rechnungen
Erzeugen Sie im \matlab-Skript °basis1° (File: °basis1.m°)
die Variablen °a° und °b° und geben Sie ihnen die Werte 
°3.2° und °2.1°.

Berechnen Sie nun folgende Größen, wobei links die Variablennamen stehen. Für das automatische Testen ist es unbedingt notwendig, 
dass Sie \red{genau diese Namen} für Ihre Variablen verwenden!

$$ 
\begin{aligned}
\verb°sum3° & = a + b \\
\verb°diff3° & = a - b \\
\verb°prod3° & = a\cdot b \\
\verb°quot3° & = \frac{a}{b} \\
\verb°pot3° & = a^{b} \\ 
\verb°wurzel3° & = \sqrt{a} \\
\verb°root3c°  & = a^{1/3} \\
\verb°expo3°   & = \mathrm{e}^{-a} \\
\verb°trig1c°  & = \sin a \\
\verb°trig2c°  & = \sin(a+b) \\
\verb°trig3c°  & = \cos \pi a
\end{aligned}
$$

\hw 

Vergessen Sie nicht den Strichpunkt am Ende einer Anweisungszeile. 
Kein abgegebenes Beispiel soll eine Ausgabe erzeugen, die nur durch das Weglassen des Strichpunktes am 
Ende einer Zeile entsteht (Infos dazu auch im \wikilink 
unter: \mltutorhint{Strichpunkt}{MLTutor Hints}).

\hw 

In keiner Testaufgabe soll der \matlab-Befehl \matrefe{clear} verwendet
werden. Infos dazu auch im \wikilink unter:
\mltutorhint{clear}{MLTutor Hints}.

\hw 

\matlab-Hilfe zu einzelnen Befehlen finden Sie unter \matrefe{sqrt}, \matrefe{exp}, 
\matrefe{sin}, \matrefe{cos}, \matrefe{pi}. Die Operatoren °+°,  °-°, °*° und
°/° bezeichnet man als \matref{arithmetische Operatoren}{arithmeticoperators}.

\hw 

Die Zahl $e$ als solches existiert in \matlab nicht. Sie muss mit Hilfe
der Funktion \matrefe{exp} konstruiert werden.

\hw 

Einen Überblick über \MatlabReferenceMathematics und
im Speziellen über \MatlabReferenceMathematicsElementaryMath bietet die \matlab-Hilfe.

\hw 

Das entsprechende Kapitel im Skriptum finden Sie im Tab "Hints und Links".

\hw 

Zur Vorbereitung auf die Übung gibt es \matlabpublish{simplestart1}{hier} noch ein einfaches Beispiel, das sich mit
Skalaren beschäftigt. 

