

# Lineares Gleichungssystem; 

Gegeben sind eine Matrix $\mathbf{A}$ und ein Vektor $\mathbf{b}$:
$$
  \mathbf{A} = 
  \begin{bmatrix}
    6 & 1 & -3 \\
		8 & 8 & 0 \\
		-2 & 0 &  1
  \end{bmatrix}
  ,\quad
  \mathbf{b} =
  \begin{bmatrix}
    3 \\ 3 \\ 11
  \end{bmatrix}
$$

Schreiben Sie ein \python Skript

		solve,

in dem Sie das Gleichungssystem


*  $\mathbf{Ax} = \mathbf{b}$


lösen.

Geben Sie den Vektor
unter Verwendung des Befehles \pyref{print} folgendermaßen aus:
 
x = 'Werte von x'

