
# Sortieren von Daten in 2D
Die Übung beschäftigt sich mit dem Sortieren von ungeordneten Daten in zwei
Dimensionen. In diesem Beispiel sind Messdaten $y(x)$ in einem Datenfile
gegeben. Diese Daten sind völlig ungeordnet und müssen so geordnet und
geplottet werden, dass $x$ monoton steigt.

Die Aufgabe ist im Skript °sort_data_2d° zu erledigen, der entsprechende
Datenfile heißt °s_data_2d.dat° mit zwei Spalten für $x$- und $y$-Werte
(\matrefe{load}).

Nach dem Sortieren (\matrefe{sort}) sollen die ursprünglichen Daten (rot,
punktiert) und die sortierten Daten (blau, durchgehend) in einem
\matref{Plot}{plot} gezeichnet werden.

\hw 

Wichtig ist darauf zu achten, dass \matrefe{sort} zwei Ausgabeparameter hat.

