
# Steuerstrukturen: if-Entscheidung
Bei diesem Beispiel sollen Sie im Skript °if_test° den Umgang mit
\matrefe{if}-Entscheidungen ausprobieren und irgendeinen Versuch abgeben. 
Für einen positiven Test muss ihr Versuch mindestens je einmal
\matrefe{if}, \matrefe{elseif} und \matrefe{else} enthalten.

Die in der Vorlesung gezeigten Beispiele sind im Tab °Extra Files°
zugänglich.




  
*  °if_test1°: Einfaches \matrefe{if}, verschiedene Schreibweisen.
  
*  °if_test2°: In Kombination mit logischen Operatoren.
  
*  °if_test3°: Geschachteltes \matrefe{if}.
  
*  °if_test4°: Keine Matrizen in Bedingungen, \matrefe{all},
  \matrefe{any}.
  
*  °if_test5°: Reihenfolge der Bedingungen ist wichtig, da immer nur
  der Zweig mit der ersten richtigen Bedingung ausgeführt wird.

*  °if_test6°: Noch ein if mit \matrefe{all} und \matrefe{any}.



