# Erzeugung von Vektoren
Erzeugen Sie im \matlab-Skript °vector_create° einige Zeilenvektoren. Dabei sollen den Variablen
folgende Werte zugewiesen werden:

------|-----------------------------------------
°q_1° | Nullen - 8 Spalten 
°q_2° | Einsen - 7 Spalten 
°q_3° | Fünfer - 6 Spalten
°r_1° | 0 bis 5 mit Abstand 1 
°r_2° | 0 bis 5 mit Abstand 0.5
°r_3° | 5 bis 0 mit (absolutem) Abstand 1
°s_1° | Leeres Feld
°t_1° | 90 Punkte im geschlossenen Interval $[0,5]$ (linearer Abstand) 
°t_2° | 80 Punkte im geschlossenen Interval $[5,0]$ (linearer Abstand) 
°u_1° | 9 Punkte im geschlossenen Interval $[10^{-2},10^{2}]$ (logarithmischer Abstand) 
°u_2° | Zehner-Logarithmus ($\log_{10}$) von °u_1° 
°v_1° | 6 Punkte im geschlossenen Interval $[e^{-2},e^{3}]$ (logarithmischer Abstand) 
°v_2° | Natürlicher Logarithmus ($\ln$) von °v_1° 
°w_1° | Die Zahlen $[1, 2, 4, 8, \dots, 1024]$ berechnet mit einer Vektoroperation
°w_2° | Die Zahlen  $[1, \frac{1}{2}, \frac{1}{4}, \frac{1}{8},\dots, \frac{1}{32}]$ berechnet mit einer Vektoroperation
°x_1° | Fakultät  $[0!, 1!, 2!, \dots, 6!]$ berechnet mit einem Befehl

Versuchen Sie unter Benutzung der \matlab-Hilfe die entsprechenden Befehle zu finden. Für diesen 
ersten Teil gibt es Hilfe im Tab "Used Functions".

Da es extrem wichtig ist, dass man sich mit dem \matlab-Hilfesystem zurechtfindet, werden für die 
folgende Teilaufgabe keine 
Befehle angeführt. Starten Sie also den \matlab \matrefe{helpbrowser} und versuchen Sie etwas zum 
Thema Zufallszahlen zu finden. 

Eine Strategie wäre, z.B., die Suche in der Hilfe auf \matlab einzuschränken 
(Im helpbrowser: File; Preferences; Help; Selected Products; Matlab) und dann zu suchen. Die englischen 
Bezeichnungen sind "random numbers", "uniform distribution", "normal distribution", "mean value", 
"standard deviation".

Eine andere Möglichkeit wäre im Content-Bereich entweder bei "functions", "mathematics", 
"elementary matrices" zu blättern und zu schauen, ob man hier etwas findet. Möglich ist es auch im 
Bereich "user guide", "mathematics".

Fragen Sie nicht sofort Kollegen, sondern versuchen Sie es selbst. Nach eigenen Versuchen helfen wir 
Ihnen gerne.

Erzeugen Sie nun folgende Zeilenvektoren mit Zufallszahlen: 

------|-----------------------------------------
°y_1° | 10 gleichverteilte Zufallszahlen im offenen Intervall $]0,1[$
°y_2° | 10 normalverteilte Zufallszahlen (Mittelwert 0, Standardabweichung 1)
°y_3° | 10 gleichverteilte ganzzahlige Zufallszahlen im geschlossenen Intervall $[5,15]$

 





