
# Ellipse - Plot
Diese Übung beschäftigt sich mit der Berechnung der Koordinaten einer Ellipse
sowie deren graphische Darstellung. Schreiben Sie im \matlab-Skript
°ellipso_plot° (Datei: °ellipso_plot.m°), ein Programm, welches die
Koordinaten der Ellipse mit Hilfe Ihrer eigenen Funktion °ellipso°
berechnet und anschließend graphisch darstellt.

Definieren Sie dafür im Skript die Variablen °a° und °b° (Werte:
°5° bzw. °3°) und rufen Sie danach die Funktion mit diesen Variablen
als Inputparameter auf. Die Outputvariablen der Funktion sollen unter °x°
bzw. °y° gespeichert werden.
Der Plot soll die Ellipse als grüne, durchgezogene Linie darstellen. Erstellen
Sie außerdem eine sinnvolle Achsenbeschriftung.

\hw 

Fügen Sie zur besseren
Darstellung nach dem Plot-Befehl ein \matref{axis equal}{axis} ein.

