
# Steuerstrukturen: for-Schleife
Bei diesem Beispiel sollen Sie im Skript °for_test° den Umgang mit
\matrefe{for}-Schleifen ausprobieren und irgendeinen Versuch abgeben. 
Für einen positiven Test muss zumindest eine \matrefe{for}-Schleife enthalten
sein.

Die in der Vorlesung gezeigten Beispiele sind im Tab °Extra Files°
zugänglich.




  
*  °for_test1°: normaler Index, bzw. Zeilenvektor.
  
*  °for_test2°: Spaltenvektor, bzw. Matrix. Beobachten Sie den
  Unterschied zu °for_test1°.
  
*  °for_test3°: Aufsummieren von Vektoren, bzw. Produkt. Natürlich
  kann man ähnliche Beispiele mit \matrefe{sum}, bzw. \matrefe{prod} in
  schönerer Weise lösen.
  
*  °for_test4°: Vorzeitiger Ausstieg aus Schleife mit \matrefe{break}.
  
*  °for_test5°: Vorzeitige Rückkehr zum Anfang mit \matrefe{continue}.
  
*  °for_test6°: Modifikation der Schleifenvariablen innerhalb der
  Schleife. Dies ist ein sehr unschönes Programmieren, hat aber auf den Ablauf
  der Schleife selbst keinen Einfluss.
  
*  °for_test7°: Schleifendurchlauf durch eine gesamte Matrix,
  beachten Sie die Reihenfolge.
  
*  °for_test8°: Schleifendurchlauf durch eine Zelle (\matrefe{cell}) 




