
# Steuerstrukturen: while-Schleife
Bei diesem Beispiel sollen Sie im Skript °while_test° den Umgang mit
\matrefe{while}-Schleifen ausprobieren und irgendeinen Versuch abgeben. 
Für einen positiven Test muss zumindest eine \matrefe{while}-Schleife enthalten
sein.

Die in der Vorlesung gezeigten Beispiele sind im Tab °Extra Files°
zugänglich.




  
*  °while_test1°: Bedingte Schleife, Gefahr unendliche Schleife.
  
*  °while_test2°: Bedingte Schleife, zwei Änderungen.
  
*  °while_test3°: Keine Matrizen als Bedingung, (\matrefe{all},
  \matrefe{any}).




