
# Animation 
In einem \python-\pyref{Skript}{script}

		simpleanim 

soll eine Kurve animiert werden.

Erzeugen Sie dazu einen Vektor $x$ mit $100$ Punkten zwischen $0$ und
$1\cdot \pi$, berechnen dann $y = sin  x$, erzeugen einen Vektor $a$ mit
$34$ Punkten zwischen $0$ und $\pi$, und berechnen dann $a = sin  a$.

Vor der eigentlichen Animation erzeugen Sie eine \mplotref{figure}. Um später die °xdata° und die°ydata° verändern zu können, benötigen Sie ein Objekt, das selbige enthält. Dies erhalten sie z.B. mit
line, = plt.plot(0,0)
Der Beistrich ist entscheidend, da die Funktion plot mehrere Argumente zurückgibt, wir aber nur am ersten, der line, interessier sind.
Setzen Sie die Achsenlimits auf das Minimum und Maximum von $x$,
bzw. auf $-1$ und $1$.

In einer Schleife über alle Werte von $a_n$, setzen Sie nun für die Linie die
°xdata° auf $x$ und die °ydata° auf $a_k \cdot y$ (line.set_xdata bzw. line.set_ydata).
Führen Sie danach jeweils \mplotref{draw} und \mplotref{pause(t)}{pause}, wobei $t$
eine sehr kurze Zeit in Sekunden ist.

Nun sollte sich in der Graphik die Kurve von der Null-Linie zum Sinus mit der
Amplitude $1$ und wieder zurück zur Null-Linie bewegen. 

